source 'https://rubygems.org'

gem 'aws-sdk-ec2'
gem 'aws-sdk-autoscaling'
gem 'aws-sdk-elasticloadbalancing'
gem 'aws-sdk-elasticloadbalancingv2'
gem 'aws-sdk-iam', '~>1.5'

gem 'rexml'
gem 'bosh_common'
gem 'bosh_cpi'

group :development, :test do
  gem 'pry-byebug'
  gem 'rspec'
  gem 'rake'
  gem 'rubocop'
  gem 'webmock'
end
