source 'https://rubygems.org'

gem 'aws-sdk',     '~>2.10'
gem 'bosh_common', '1.3262.24.0'
gem 'bosh_cpi',    '~>2.4'

group :development, :test do
  gem 'netaddr'
  gem 'pry-byebug', '~>3.4'
  gem 'rspec',      '~>3.5'
  gem 'rake',       '~>12.0'
  gem 'webmock'
end
