#!/bin/bash

set -ex

tmp_dir=$(mktemp -dt aws-cpi-XXXXXXXX)

cleanup() {  
  rm -rf $tmp_dir
}

trap EXIT cleanup

aws_cpi_dir=$(cd $(dirname $0)/../ && pwd)
aws_cpi_gems_dir=$aws_cpi_dir/src/bosh_aws_cpi
rm -rf $aws_cpi_gems_dir
mkdir -p $aws_cpi_gems_dir

(
  cd $tmp_dir
  cat > 'Gemfile' <<EOF
source "https://rubygems.org"

gem "bosh_aws_cpi"    
EOF

  bundle install --path .

  cp -r ruby/*/cache/*.gem ${aws_cpi_gems_dir}
)
