#!/bin/bash

set -ex

aws_cpi_dir=$(cd $(dirname $0)/../ && pwd)
aws_cpi_gems_dir=$aws_cpi_dir/src/bosh_aws_cpi

cleanup() {
  cd $aws_cpi_gems_dir
  rm Gemfile*
}

trap cleanup EXIT

(
  cd $aws_cpi_gems_dir
  cat > 'Gemfile' <<EOF
source "https://rubygems.org"

gem "bosh_aws_cpi"
EOF

  bundle package
)
